# Generated by Django 2.1.4 on 2018-12-31 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField(max_length=7000)),
                ('author', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2018)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='release_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ReleaseYear'),
        ),
        migrations.AddField(
            model_name='article',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Theme'),
        ),
        migrations.AddField(
            model_name='article',
            name='release_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ReleaseYear'),
        ),
    ]
