# Generated by Django 2.1.4 on 2019-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190103_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='url_name',
            field=models.CharField(default='attualita', max_length=100),
            preserve_default=False,
        ),
    ]
